security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Security\VermittlerUser: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost:      15
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Security\VermittlerUser
                property: email
    firewalls:
        login:
            pattern: ^/foo/login
            stateless: true
            json_login:
                check_path: /foo/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/foo
            stateless: true
            jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI
        - { path: ^/docs, roles: PUBLIC_ACCESS } # Allows accessing API documentations and Swagger UI docs
        - { path: ^/foo/login, roles: PUBLIC_ACCESS }
        - { path: ^/foo, roles: IS_AUTHENTICATED_FULLY }
