App\Entity\Adresse:
  attributes:
    strasse:
      groups: ['adresse:read', 'adresse:write', 'kunde:read']
    plz:
      groups: ['adresse:read', 'adresse:write', 'kunde:read']
    ort:
      groups: ['adresse:read', 'adresse:write', 'kunde:read']
    bundesland:
      groups: ['adresse:read', 'adresse:write', 'kunde:read']
    details:
      groups: ['adresse:read', 'kunde:read']