App\Entity\KundeAdresse:
  attributes:
    kunde_id:
      groups: ['kundeAdresse:write', 'adresse:write']
    adresse_id:
      groups: ['kundeAdresse:write', 'adresse:write']
    geschaeftlich:
      groups: ['kundeAdresse:read', 'kundeAdresse:write', 'adresse:read', 'adresse:write', 'kunde:read']
    rechnungsadresse:
      groups: ['kundeAdresse:read', 'kundeAdresse:write', 'adresse:read', 'adresse:write', 'kunde:read']